### ISSUE TITLE
Term4 -9.24

### ISSUE THREAD

**Issue by SeungjinJung** [projectgteam/study#4]
4.Views and the View Hierarchy   드디어 뷰!

**Comment by SeungjinJung** [comment]
<img width="319" alt="2015-09-24 11 54 56" src="https://cloud.githubusercontent.com/assets/853975/10076695/b326d300-6317-11e5-8ab3-96e12616f38c.png">

**Comment by leehosung** [comment]
![screen shot 2015-09-25 at 3 02 30 pm](https://cloud.githubusercontent.com/assets/2469766/10098620/9811db72-63bd-11e5-8054-96ede637b3ab.png)
