### ISSUE TITLE
Term5 - 9월 26일

### ISSUE THREAD

**Issue by reggae1027** [projectgteam/study#5]
저는 클린 코드를 위한 테스트 주도 개발 시작합니다.
Chapter 1 & 2

**Comment by leehosung** [comment]
굳잡!

나름 재미있을 겁니다. :)

**Comment by leehosung** [comment]
저는 이번에 5장 Views: Redrawing and UIScrollView 를 읽습니다.

**Comment by leehosung** [comment]
이번장은 가볍게 넘어가는 군요. 

IOS에서 root controller 가 반드시 있어야 하는 문제 때문에 UIViewController 에서 터치 이벤트를 받아서 다시 view 로 넘겨주는 방식을 사용했습니다.

![screen shot 2015-09-26 at 1 43 09 pm](https://cloud.githubusercontent.com/assets/2469766/10115874/d41d884a-6454-11e5-82db-9566887cba7e.png)

**Comment by reggae1027** [comment]
Intro라 가볍게 돌파합니다.
![2015-09-26 11 43 42](https://cloud.githubusercontent.com/assets/12426258/10118061/8bbc0bcc-64a8-11e5-9492-6ddcc9138497.png)

**Comment by SeungjinJung** [comment]
<img width="320" alt="2015-09-29 8 18 09" src="https://cloud.githubusercontent.com/assets/853975/10152553/4fec077c-668e-11e5-9fa8-f71db3c7ff08.png">
