### ISSUE TITLE
Term6 - 9월 28일

### ISSUE THREAD

**Issue by leehosung** [projectgteam/study#6]
저는 6장 - ViewControllers 를 읽습니다. 

그래도 이렇게 이틀에 두장씩이라도 목표를 정해놓고 읽으니 진도가 잘 나가고 있는 것 같아요!

**Comment by reggae1027** [comment]
Chapter 3,4 갑니다. 꾸준하게 가봅시다 :)

**Comment by leehosung** [comment]
![screen shot 2015-09-29 at 12 30 18 am](https://cloud.githubusercontent.com/assets/2469766/10140187/57fb53c0-6641-11e5-90c0-1b1530750984.png)
탭바를 사용해 봤습니다~

**Comment by reggae1027** [comment]
selenium으로 브라우저 테스트하는 것 신기하네요.

![2015-09-29 1 14 02](https://cloud.githubusercontent.com/assets/12426258/10141426/772d16e2-6647-11e5-9fff-f3626c685f68.png)

**Comment by SeungjinJung** [comment]
![Uploading 스크린샷 2015-09-29 오전 9.40.49.png…]()
