### ISSUE TITLE
Term #9 - 10월 3일

### ISSUE THREAD

**Issue by SeungjinJung** [projectgteam/study#9]
저는 순서를 조금 바꿔서 11단원 카메라를 먼저 읽어보겠습니다~

**Comment by taehoonan** [comment]
전 coursera에서 Management of Fashion and Luxury Companies 강의로 스터디 시작할게요:) 오늘은 week1 마스터하는걸로!

**Comment by SeungjinJung** [comment]
![2015-10-02 11 37 06](https://cloud.githubusercontent.com/assets/853975/10238387/10a7484c-68fa-11e5-9969-578ff1c4f1be.png)

* imagepicker (카메라, 앨범)
* background touch 시 keyboard dismiss
* image 파일로 저장

**Comment by leehosung** [comment]
저는 9장 Editing UITableView 를 읽습니다. (책도 벌써 34%가 되었군요)

**Comment by taehoonan** [comment]
1강 마쳤고 이어서 2강으로!
패션과 럭셔리에 각각에 대해 다른 교수가 강의를 하는데, 산업에 대한 기본개념 익히기에 좋네요.
(패션쪽 교수님은 자막을 꼭 켜야된다는 ㅜ)
- 패션트렌드 싸이클을 보면 1) innovators(트렌드의 시작) 2) trend setters(에디터,블로거,VIP..) 3) mainstream 4) last adoptors의 순으로 간다는데 우리 서비스는 trend setters, mainstream phase의 구매자가 대상이 되겠군요. (https://www.coursera.org/learn/mafash/lecture/zdsSA/new-trends)
- "Luxury is not an object, not replicable, not just expensive, not easy, not fast.." (https://www.coursera.org/learn/mafash/lecture/oCo5Z/what-is-luxury-not)

<img width="597" alt="2015-10-03 2 35 47" src="https://cloud.githubusercontent.com/assets/14917529/10261651/e2b6ad2c-69dc-11e5-94f3-916f83bf28ac.png">

추가로 세계 4대 패션쇼의 주요브랜드 런웨이 영상을 제공하는 유투브채널(https://www.youtube.com/user/fashiontvhotplus)도 공유해요.

**Comment by reggae1027** [comment]
<img width="632" alt="2015-10-04 1 02 34" src="https://cloud.githubusercontent.com/assets/12426258/10263738/b3d1b892-6a33-11e5-9070-1299b6815cc5.png">

6장도 재밌게 잘 했습니다. 책이 참 꼼꼼해서 좋네요!

**Comment by leehosung** [comment]
![screen shot 2015-10-04 at 5 01 23 pm](https://cloud.githubusercontent.com/assets/2469766/10266989/a6eb6e4e-6ab9-11e5-8e22-3c071a286780.png)

하악 꼴등꼴등
